// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrnitpqkjchudeoxjsvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indybml0cHFramNodWRlb3hqc3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjk5MzEsImV4cCI6MjA3Mjg0NTkzMX0.rMyorVSSjbvQPaUztXvDPfRtCV4ihmsVQ5oC6s5RthM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});